### ISSUE TITLE
There seems to be deliberate modification of function names and deletion of key code files in the code, and too many bugs make the program not work.

### ISSUE THREAD

**Issue by 1m2bert** [ChocoWu/MRE-ISE#3]
For example, in 'run.py', line 15, where is the definition of MREProcessor, MREDataset? 

In ' run.py', line 16, where is the Trainer in 'cores.gene.model'? but i've found it in 'cores.gene.train'?

In 'cores/gene/_pycache_/train.py', where is the modules.metrics?

Why are you trying to do with that, are you trying to hide something?  The code is really confusing to change like that.

**Comment by ChocoWu** [comment]
Thx for the attention.
I have added the `metrics.py` file, and will check through the code and update it.
