### ISSUE TITLE
关于场景图

### ISSUE THREAD

**Issue by M1091027** [ChocoWu/MRE-ISE#5]
RelTR中的inference.py运行后得到的是一张图，请问您代码tsg文件夹的json文件是如何得到的呢

**Comment by 1223243** [comment]
哥，你跑起来了吗

**Comment by 1223243** [comment]
> RelTR中的 inference.py 运行后得到的是一张图，请问您代码tsg文件夹的json文件是如何得到的呢

哥，你跑起来了吗

**Comment by ChocoWu** [comment]
@M1091027，感谢对我们工作的关注。
首先，RelTR是用于解析vsg的。其次，原始RelTR中的inference.py代码的确是通过生成一张图片来表示vsg的，因此我们可以通过保存画图之间的bounding box以及类别，就可以得到目标vsg。具体可参考https://github.com/ChocoWu/MRE-ISE/blob/main/VSG/RelTR_parser/visual_scene_graph.py
